server:
  port: 8091
  error:
    include-stacktrace: never
spring:
  data:
    web:
      pageable:
        max-page-size: 1000
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL9Dialect"
        hbm2ddl:
          auto: update
logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: INFO
