server:
  port: 8091
  error:
    include-stacktrace: never
spring:
  data:
    web:
      pageable:
        max-page-size: 1000
  datasource:
    url: jdbc:postgres://ec2-54-228-174-49.eu-west-1.compute.amazonaws.com:5432/d1id11qdj95h7r?user=aselxrnupqgazm&password=77b923813850ffe5143d3fac63ef968700e736c2da2a15e0711e19956bd6ebfa&sslmode=require
    password: 77b923813850ffe5143d3fac63ef968700e736c2da2a15e0711e19956bd6ebfa
    username: aselxrnupqgazm
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL9Dialect"
        hbm2ddl:
          auto: update
logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: INFO
