server:
  port: 8091
  error:
    include-stacktrace: never
    include-message: always
spring:
  data:
    web:
      pageable:
        max-page-size: 1000
  datasource:
    url: ${ACTUAL_DATABASE_URL}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQL9Dialect"
        hbm2ddl:
          auto: update
logging:
  level:
    org:
      springframework:
        security: DEBUG
    root: INFO
security:
  #Not defining secret-signing-key will cause a new random key to be created each time the server starts
  secret-signing-key: ${SIGNING_KEY} #Might need to be updated once in a while
