name: Run Gradle on PRs
on: pull_request
jobs:
  gradle:
    runs-on: [ ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1.3.3
      with:
        gradle-version: current
        arguments: spotlessCheck test
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
